### ISSUE TITLE
PB Displaying Name since 1.1.4

### ISSUE THREAD

**Issue by panteror** [stevotvr/phpbb-steamstatus#3]
Hi,

I have a problem since new version 1.1.4.
When i open a topic with the steam block, the name is displayed first like this (screen1) then after 60 seconds (maybe the setting in ACP), the name is displayed correctly.
In 1.1.3 I didn't have the problem, the name was displayed correctly at first.
Thanks

![steamstatus1 4](https://user-images.githubusercontent.com/13719235/34479594-fc448522-efa7-11e7-9aa6-04f85c8ce1ea.png)
![steamstatus1 4_2](https://user-images.githubusercontent.com/13719235/34479595-fc640c30-efa7-11e7-9624-0e0c74f5877c.png)

my settings
![steam status_settings](https://user-images.githubusercontent.com/13719235/34479872-5e5d29de-efa9-11e7-85a0-553bfa34d466.png)

**Comment by stevotvr** [comment]
Fixed in 1.1.5.
