### ISSUE TITLE
Steam Status Not Authenticating/Linking

### ISSUE THREAD

**Issue by ghost** [stevotvr/phpbb-steamstatus#5]
Hi Steve,

I saw a message on the phpbb forum with a similar issue.  3.2.5 phpbb with 1.2.1 extension is returning an unknown error when trying to sign in.  It worked for the first day, and then after that it stopped again.  Any solution to this besides the ones already mentioned?  (turning off https and editing the one file?)

Thanks!

**Comment by stevotvr** [comment]
I haven't been able to reproduce the problem. The other person wasn't seeing an error message, so your issue is a little different. If you can show me the output of phpinfo on your server and any error messages, I can try to figure out what the problem is.

**Comment by stevotvr** [comment]
I tried to create an account but the activation email hasn't come. The same thing happened on the other board. Can you activate my account so I can look at the problem myself?

**Comment by ghost** [comment]
Sure, not a problem!  I’m not sure why, but some of the emails coming from the board are going into spam folders.

I’ll have to look into that also.

Sent from Mail for Windows 10

**Comment by stevotvr** [comment]
Thanks. I found the email in my spam folder. I didn't think to check there.

It looks like your board's path and domain settings are incorrect. It seems to be set up as if your board is at /forums instead of the forums subdomain. I was able to link my account by fixing the realm domain.

**Comment by ghost** [comment]
The domain settings for the Steam API key?  So, I should be typing in www.purplemilkbox.com/forums  instead of http://forums.purplemilkbox.com?


Sent from Mail for Windows 10

**Comment by stevotvr** [comment]
No, that doesn't seem to matter. I'm referring to the server settings for your phpBB installation (in the ACP).

**Comment by ghost** [comment]
Will this require a reinstallation?  Or I can change this from the ACP?  

Sent from Mail for Windows 10

**Comment by stevotvr** [comment]
Go to the _ACP > General tab > Server configuration > Server settings > Server URL settings section_ and set _Domain name_ to `forums.purplemilkbox.com` and _Script path_ to `/`.

**Comment by ghost** [comment]
Awesome!  Thank you so much for your help Steve!  I really appreciate it!  

Sent from Mail for Windows 10

**Comment by stevotvr** [comment]
No problem. It's good to know it's not a problem with the extension.

I'll get an update released soon to fix the broken image link. You might be able to fix that in the meantime by leaving _Script path_ blank.
