### ISSUE TITLE
Error on Login

### ISSUE THREAD

**Issue by Alphaverse** [stevotvr/phpbb-steamstatus#6]
Hello,

when I try to login with steam to connect the account on the steam login page an error occurs after pressing login. I don't know what to do... It only says 'Error'.. 

I hope you will be able to help me.

Alphaverse

**Comment by stevotvr** [comment]
Make sure the server URL settings on your board are correct.

**Comment by Alphaverse** [comment]
How can I found out if they are? Because I am pretty sure they are correct but I don't really know what could be wrong.

**Comment by stevotvr** [comment]
Can you send me a link to your board? I might be able to see the problem.

**Comment by Alphaverse** [comment]
http://www.alphavex.com/index.php

**Comment by stevotvr** [comment]
I can't find the UCP panel for the extension. Is the extension enabled with a valid API key? Or, if you changed the required permissions, could you give my account access to link Steam account?

**Comment by Alphaverse** [comment]
I reactivated the extension and changed your rank.. I hope you will find something.

**Comment by stevotvr** [comment]
Sorry, I still don't see the tab in the UCP. Either you didn't set the API key or I don't have the "Can link account to Steam" permission.

**Comment by Alphaverse** [comment]
I've just given you the permissions again. 

It should be setup correctly because it displays for me in UCP->Profile->Link steam account

**Comment by stevotvr** [comment]
I still don't see it.

Anyway, if you aren't already, you can try using v1.2.2: https://github.com/stevotvr/phpbb-steamstatus/releases/tag/v1.2.2.

**Comment by Alphaverse** [comment]
I updated the version. If I try to connect to steam now I get this error:

Received error: realm and return_to do not match

**Comment by stevotvr** [comment]
What is the "Sign in through Steam" image linking to?

**Comment by Alphaverse** [comment]
https://steamcommunity.com/openid/login?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=checkid_setup&openid.return_to=http%3A%2F%2Fwww.alphavex.com%2Fucp.php%3Fi%3D-stevotvr-steamstatus-ucp-main_module%26mode%3Dmain&openid.realm=https%3A%2F%2Fwww.alphavex.com&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select

You should have the permissions now. I forgot to activate the account.

**Comment by stevotvr** [comment]
Make sure that "Server protocol" is set to http:// in your Server URL settings.

**Comment by Alphaverse** [comment]
I changed it. Now I don't see an error and just get redirected to the connect page. But nothing else happens. There is still the button to connect the steam account but it doesn't seem like anything was connected.

**Comment by stevotvr** [comment]
I can see it now. Everything looks fine in the front end, so something must be going wrong in the back end. Did you try unchecking "Use HTTPS" in the Steam Status settings? Also, check your error log for any errors.

**Comment by Alphaverse** [comment]
Yes I disabled "Use HTTPS" and there are no errors :/

EDIT: I reactivated "Use HTTPS" and now it seems to work! Thank you! <3 :D

**Comment by stevotvr** [comment]
It's working for me, too. That's weird, but at least it works now.
